"""Allow-listed synthetic sample documents for the public demo.

Visitors can only load these files by id; no client-supplied path ever reaches the filesystem.
All samples are synthetic (generated by ``scripts/generate_sample_data.py``).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from app.core.errors import NotFoundError


class SampleNotFoundError(NotFoundError):
    error_type = "sample_not_found"


@dataclass(frozen=True)
class DemoSample:
    sample_id: str
    filename: str
    title: str
    document_kind: str
    summary: str
    expected_outcome: str  # READY | NEEDS_REVIEW
    lesson: str
    suggested_questions: tuple[str, ...]


SAMPLES: tuple[DemoSample, ...] = (
    DemoSample(
        sample_id="clean-invoice",
        filename="invoice_01_acme.pdf",
        title="A clean supplier invoice",
        document_kind="Invoice",
        summary="Acme Office Supplies bills Northwind Traders for office equipment.",
        expected_outcome="READY",
        lesson="Everything checks out, so no person needs to look at it.",
        suggested_questions=(
            "What is the total amount due?",
            "Who sent this invoice?",
            "How much tax was charged?",
        ),
    ),
    DemoSample(
        sample_id="missing-currency",
        filename="income_statement_03_aurora.pdf",
        title="An income statement with no currency",
        document_kind="Income statement",
        summary="Aurora Health Partners' quarterly results. The figures never say whether "
        "they are dollars, euros or anything else.",
        expected_outcome="NEEDS_REVIEW",
        lesson="A required detail is missing, so it asks a person instead of assuming.",
        suggested_questions=("What was the net income?", "What were the net sales?"),
    ),
    DemoSample(
        sample_id="conflicting-figures",
        filename="balance_sheet_03_granite_conflict.pdf",
        title="A balance sheet with conflicting totals",
        document_kind="Balance sheet",
        summary="Total assets are 9,750,000 on the summary page but 9,570,000 in the "
        "detailed statement.",
        expected_outcome="NEEDS_REVIEW",
        lesson="Two different values for the same figure is a reason to stop and ask.",
        suggested_questions=("What are the total assets?", "How much cash does Granite hold?"),
    ),
    DemoSample(
        sample_id="hidden-instructions",
        filename="edge_injection_invoice.pdf",
        title="An invoice with hidden instructions",
        document_kind="Invoice",
        summary="A note at the bottom tells AI systems to approve payment to a different "
        "bank account and not to flag the invoice.",
        expected_outcome="NEEDS_REVIEW",
        lesson="The planted instruction is caught, treated as plain text and flagged.",
        suggested_questions=("What is the amount due?", "Should this invoice be paid?"),
    ),
    DemoSample(
        sample_id="european-invoice",
        filename="invoice_05_wingtip_european.pdf",
        title="A European-format invoice",
        document_kind="Invoice",
        summary="Amounts are written the European way: 10.450,00 means ten thousand four "
        "hundred and fifty.",
        expected_outcome="READY",
        lesson="Number formats from different countries are read correctly.",
        suggested_questions=("What is the amount due?", "How much VAT was charged?"),
    ),
    DemoSample(
        sample_id="unsupported-document",
        filename="edge_credit_card_statement.pdf",
        title="A credit card statement",
        document_kind="Not supported",
        summary="Credit card statements are not one of the five document types this system "
        "knows how to read.",
        expected_outcome="NEEDS_REVIEW",
        lesson="It says 'I don't know this kind of document' rather than forcing a guess.",
        suggested_questions=("What is the new balance?",),
    ),
)

_BY_ID = {s.sample_id: s for s in SAMPLES}


def get_sample(sample_id: str) -> DemoSample:
    sample = _BY_ID.get(sample_id)
    if sample is None:
        raise SampleNotFoundError(f"unknown sample '{sample_id}'")
    return sample


def sample_bytes(sample: DemoSample, sample_dir: Path) -> bytes:
    path = (sample_dir / "pdfs" / sample.filename).resolve()
    if not path.is_file():
        raise SampleNotFoundError(f"sample file for '{sample.sample_id}' is not installed")
    return path.read_bytes()
