/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Corpus
         * @description Question across all indexed documents (optionally metadata-filtered).
         *
         *     Demo visitors only search their own workspace.
         */
        post: operations["ask_corpus_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Audit Chain
         * @description Recompute the audit hash chain to detect after-the-fact modification.
         */
        get: operations["verify_audit_chain_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Samples
         * @description Synthetic sample documents a visitor can load with one click.
         */
        get: operations["list_samples_demo_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/samples/{sample_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Sample
         * @description Copy an allow-listed sample into the caller's workspace (same path as an upload).
         */
        post: operations["load_sample_demo_samples__sample_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/samples/{sample_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sample File
         * @description The original sample PDF, for side-by-side viewing.
         */
        get: operations["sample_file_demo_samples__sample_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Session
         * @description Start (or keep) an anonymous visitor session bound to a private workspace.
         */
        post: operations["start_session_demo_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Status
         * @description Which AI engine is answering right now, and the visitor's remaining allowance.
         */
        get: operations["demo_status_demo_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Document */
        post: operations["ask_document_documents__document_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_documents__document_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Document Audit
         * @description Tamper check for this document's audit events: each hash must match its content.
         */
        get: operations["verify_document_audit_documents__document_id__audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Extractions */
        get: operations["get_extractions_documents__document_id__extractions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Document
         * @description Run (or re-run) the deterministic processing workflow synchronously.
         */
        post: operations["process_document_documents__document_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/process/background": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Document Background
         * @description Start processing in a background worker and return immediately.
         *
         *     Poll ``GET /documents/{id}``: ``status`` advances through each workflow step and
         *     ``processing`` turns false when the run has finished.
         */
        post: operations["process_document_background_documents__document_id__process_background_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drift/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Drift Report
         * @description Compare current operational data against the stored drift baseline.
         */
        get: operations["drift_report_drift_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Evaluation
         * @description Run the labelled evaluation suite in an isolated sandbox and store the result.
         *
         *     Synchronous by design for the small synthetic dataset; with a real provider this makes
         *     paid model calls (roughly 3 per document plus 1 per question).
         */
        post: operations["run_evaluation_evaluations_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + dependency checks. Unauthenticated so load balancers can probe it.
         *
         *     Returns 503 when a dependency is down so probes take the instance out of rotation.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Operational metrics from the in-process registry (JSON or Prometheus text format).
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Review */
        post: operations["approve_review_reviews__review_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Review */
        post: operations["correct_review_reviews__review_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{review_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Review */
        post: operations["reject_review_reviews__review_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /**
             * Filters
             * @description Equality filters; allowed keys: ['document_type', 'extraction_method']
             */
            filters?: {
                [key: string]: string;
            } | null;
            /** Question */
            question: string;
            /** Top K */
            top_k?: number | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Answer Id */
            answer_id: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Confidence */
            confidence: number;
            /** Document Id */
            document_id: string | null;
            /** Embedding Model */
            embedding_model: string;
            /** Groundedness */
            groundedness: number | null;
            /** Is Mock */
            is_mock: boolean;
            /** Model Name */
            model_name: string;
            /** Model Provider */
            model_provider: string;
            /** Prompt Version */
            prompt_version: string;
            /** Refusal Reason */
            refusal_reason: string | null;
            /** Refused */
            refused: boolean;
            /** Requires Review */
            requires_review: boolean;
            /** Retrieval Scores */
            retrieval_scores: number[];
            /** Review Id */
            review_id: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** AuditEvent */
        AuditEvent: {
            /** Actor */
            actor: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Document Id */
            document_id?: string | null;
            /**
             * Event Hash
             * @default
             */
            event_hash: string;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Prev Hash
             * @default
             */
            prev_hash: string;
            /**
             * Sequence
             * @default 0
             */
            sequence: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Workflow Id */
            workflow_id?: string | null;
        };
        /** AuditResponse */
        AuditResponse: {
            /** Document Id */
            document_id: string;
            /** Events */
            events: components["schemas"]["AuditEvent"][];
        };
        /** AuditVerifyResponse */
        AuditVerifyResponse: {
            /** First Broken Sequence */
            first_broken_sequence: number | null;
            /** Valid */
            valid: boolean;
        };
        /** Body_upload_document_documents_upload_post */
        Body_upload_document_documents_upload_post: {
            /**
             * File
             * @description PDF document
             */
            file: string;
        };
        /** Citation */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Page Number */
            page_number: number | null;
            /** Retrieval Score */
            retrieval_score: number;
            /** Text Snippet */
            text_snippet: string;
        };
        /** ClassificationResult */
        ClassificationResult: {
            /** Confidence */
            confidence: number;
            document_type: components["schemas"]["DocumentType"];
            /**
             * Is Mock
             * @default false
             */
            is_mock: boolean;
            /** Model Name */
            model_name: string;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /** Reasoning Summary */
            reasoning_summary: string;
            /** Requires Review */
            requires_review: boolean;
        };
        /** DemoLimits */
        DemoLimits: {
            /** Documents Per Day */
            documents_per_day: number;
            /** Max Pages */
            max_pages: number;
            /** Max Upload Mb */
            max_upload_mb: number;
            /** Questions Per Day */
            questions_per_day: number;
            /** Retention Hours */
            retention_hours: number;
        };
        /** DemoSampleResponse */
        DemoSampleResponse: {
            /** Document Kind */
            document_kind: string;
            /**
             * Expected Outcome
             * @enum {string}
             */
            expected_outcome: "READY" | "NEEDS_REVIEW";
            /** Lesson */
            lesson: string;
            /** Sample Id */
            sample_id: string;
            /** Suggested Questions */
            suggested_questions: string[];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** DemoSessionResponse */
        DemoSessionResponse: {
            /** Active */
            active: boolean;
            /** Created */
            created: boolean;
            /** Ttl Hours */
            ttl_hours: number;
        };
        /** DemoStatusResponse */
        DemoStatusResponse: {
            /**
             * Ai Mode
             * @enum {string}
             */
            ai_mode: "live" | "offline";
            /** Documents Remaining */
            documents_remaining: number | null;
            limits: components["schemas"]["DemoLimits"];
            /** Model Name */
            model_name: string;
            /** Model Provider */
            model_provider: string;
            /** Offline Reason */
            offline_reason: ("budget_reached" | "configured_offline") | null;
            /** Questions Remaining */
            questions_remaining: number | null;
            /** Session Active */
            session_active: boolean;
        };
        /** DocumentAuditVerifyResponse */
        DocumentAuditVerifyResponse: {
            /** Checked Events */
            checked_events: number;
            /** First Broken Sequence */
            first_broken_sequence: number | null;
            /** Valid */
            valid: boolean;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Char Count */
            char_count: number | null;
            classification: components["schemas"]["ClassificationResult"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Workflow Id */
            current_workflow_id: string | null;
            /** Document Id */
            document_id: string;
            document_type: components["schemas"]["DocumentType"] | null;
            /** Filename */
            filename: string;
            /** Has Text Layer */
            has_text_layer: boolean;
            /** Page Count */
            page_count: number;
            /**
             * Processing
             * @description True while a background processing run is active
             * @default false
             */
            processing: boolean;
            /** Security Flags */
            security_flags: string[];
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["WorkflowStatus"];
            text_extraction_method: components["schemas"]["TextExtractionMethod"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentType
         * @enum {string}
         */
        DocumentType: "income_statement" | "balance_sheet" | "invoice" | "bank_statement" | "fund_summary" | "unknown";
        /** DriftMetric */
        DriftMetric: {
            /** Baseline */
            baseline?: unknown;
            /** Current */
            current?: unknown;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Threshold */
            threshold?: number | null;
            /** Value */
            value?: number | null;
        };
        /** DriftReport */
        DriftReport: {
            /** Alerts */
            alerts: string[];
            /** Baseline Created At */
            baseline_created_at?: string | null;
            current: components["schemas"]["DriftSnapshot"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Has Baseline */
            has_baseline: boolean;
            /** Metrics */
            metrics: components["schemas"]["DriftMetric"][];
            /** Status */
            status: string;
        };
        /** DriftSnapshot */
        DriftSnapshot: {
            /** Categorical */
            categorical: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Histograms */
            histograms: {
                [key: string]: number[];
            };
            /** Samples */
            samples?: {
                [key: string]: number;
            };
            /** Scalars */
            scalars: {
                [key: string]: number | null;
            };
            /** Versions */
            versions: {
                [key: string]: string[];
            };
            /** Window Start */
            window_start?: string | null;
        };
        /** EvaluationResult */
        EvaluationResult: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Duration S */
            duration_s: number;
            /** Gate Failures */
            gate_failures?: string[];
            /** Gate Passed */
            gate_passed: boolean;
            /** Is Mock */
            is_mock: boolean;
            /** Metrics */
            metrics: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Run Id */
            run_id: string;
        };
        /** Evidence */
        Evidence: {
            /** Page Number */
            page_number?: number | null;
            /** Snippet */
            snippet: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
        };
        /** ExtractedEntity */
        ExtractedEntity: {
            /** Alternatives */
            alternatives?: (number | string | null)[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            evidence?: components["schemas"]["Evidence"] | null;
            /** Messages */
            messages?: string[];
            /** Name */
            name: string;
            /** Raw Text */
            raw_text?: string | null;
            /** @default missing */
            validation_status: components["schemas"]["ValidationStatus"];
            /** Value */
            value?: number | string | null;
        };
        /** ExtractionResult */
        ExtractionResult: {
            /** Corrected By Review Id */
            corrected_by_review_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Document Id */
            document_id: string;
            document_type: components["schemas"]["DocumentType"];
            /** Entities */
            entities: components["schemas"]["ExtractedEntity"][];
            /** Extraction Id */
            extraction_id: string;
            /**
             * Is Mock
             * @default false
             */
            is_mock: boolean;
            /** Model Name */
            model_name: string;
            /** Overall Confidence */
            overall_confidence: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /**
             * Requires Review
             * @default false
             */
            requires_review: boolean;
            /** Review Reasons */
            review_reasons?: components["schemas"]["ReviewReason"][];
            /** Validation Issues */
            validation_issues?: components["schemas"]["ValidationIssue"][];
        };
        /** ExtractionsResponse */
        ExtractionsResponse: {
            /** Document Id */
            document_id: string;
            /** History */
            history: components["schemas"]["ExtractionResult"][];
            latest: components["schemas"]["ExtractionResult"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Mock Mode */
            mock_mode: boolean;
            /** Providers */
            providers: {
                [key: string]: string;
            };
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ProcessResponse */
        ProcessResponse: {
            document: components["schemas"]["DocumentResponse"];
            /** Document Id */
            document_id: string;
            /** Error Message */
            error_message: string | null;
            /** Error Type */
            error_type: string | null;
            /** History */
            history: components["schemas"]["WorkflowTransition"][];
            /** Review Id */
            review_id: string | null;
            /** Review Reasons */
            review_reasons: components["schemas"]["ReviewReason"][];
            status: components["schemas"]["WorkflowStatus"];
            /** Workflow Id */
            workflow_id: string;
        };
        /** ReviewCorrectionRequest */
        ReviewCorrectionRequest: {
            /** Comment */
            comment?: string | null;
            /**
             * Corrections
             * @description Field name -> corrected value; may include 'document_type'. For answer reviews use {'answer': '<text>'}.
             */
            corrections: {
                [key: string]: unknown;
            };
            /**
             * Reviewer Id
             * @description Placeholder reviewer identity; ignored when API-key auth is enabled.
             */
            reviewer_id?: string | null;
        };
        /** ReviewDecisionRequest */
        ReviewDecisionRequest: {
            /** Comment */
            comment?: string | null;
            /**
             * Reviewer Id
             * @description Placeholder reviewer identity; ignored when API-key auth is enabled.
             */
            reviewer_id?: string | null;
        };
        /** ReviewListResponse */
        ReviewListResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["ReviewResponse"][];
        };
        /**
         * ReviewReason
         * @enum {string}
         */
        ReviewReason: "low_classification_confidence" | "unknown_document_type" | "low_extraction_confidence" | "schema_validation_failed" | "validation_rule_failed" | "conflicting_values" | "missing_required_fields" | "unverified_evidence" | "insufficient_evidence" | "weak_grounding" | "low_answer_confidence" | "guardrail_triggered" | "retries_exhausted" | "ocr_unavailable" | "ocr_used";
        /** ReviewResponse */
        ReviewResponse: {
            /** Corrected Output */
            corrected_output: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Details */
            details: string[];
            /** Document Id */
            document_id: string | null;
            /** Model Version */
            model_version: string;
            /** Original Output */
            original_output: {
                [key: string]: unknown;
            };
            /** Prompt Version */
            prompt_version: string;
            /** Reasons */
            reasons: components["schemas"]["ReviewReason"][];
            /** Resolved At */
            resolved_at: string | null;
            /** Review Id */
            review_id: string;
            /** Reviewer Comment */
            reviewer_comment: string | null;
            /** Reviewer Id */
            reviewer_id: string | null;
            status: components["schemas"]["ReviewStatus"];
            /** Target Id */
            target_id: string;
            target_type: components["schemas"]["ReviewTargetType"];
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "pending" | "approved" | "rejected" | "corrected" | "superseded";
        /**
         * ReviewTargetType
         * @enum {string}
         */
        ReviewTargetType: "document_processing" | "answer";
        /**
         * Severity
         * @enum {string}
         */
        Severity: "error" | "warning";
        /**
         * TextExtractionMethod
         * @enum {string}
         */
        TextExtractionMethod: "native_pdf" | "ocr_tesseract" | "ocr_textract" | "none";
        /** UploadResponse */
        UploadResponse: {
            document: components["schemas"]["DocumentResponse"];
            /** Duplicate */
            duplicate: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Fields */
            fields?: string[];
            /** Message */
            message: string;
            /** Rule */
            rule: string;
            severity: components["schemas"]["Severity"];
        };
        /**
         * ValidationStatus
         * @enum {string}
         */
        ValidationStatus: "valid" | "invalid" | "missing" | "unverified" | "conflict" | "corrected";
        /**
         * WorkflowStatus
         * @enum {string}
         */
        WorkflowStatus: "INGESTED" | "TEXT_EXTRACTED" | "CLASSIFIED" | "ENTITIES_EXTRACTED" | "VALIDATED" | "INDEXED" | "READY" | "NEEDS_REVIEW" | "REJECTED" | "FAILED";
        /** WorkflowTransition */
        WorkflowTransition: {
            /**
             * At
             * Format: date-time
             */
            at?: string;
            from_status: components["schemas"]["WorkflowStatus"] | null;
            /** Reason */
            reason?: string | null;
            to_status: components["schemas"]["WorkflowStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_corpus_ask_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_chain_audit_verify_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_samples_demo_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSampleResponse"][];
                };
            };
        };
    };
    load_sample_demo_samples__sample_id__post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                sample_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_file_demo_samples__sample_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sample_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_demo_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_status_demo_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_documents_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_document_documents__document_id__ask_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_documents__document_id__audit_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_document_audit_documents__document_id__audit_verify_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAuditVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_extractions_documents__document_id__extractions_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_document_documents__document_id__process_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_document_background_documents__document_id__process_background_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drift_report_drift_report_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluations_evaluations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_evaluation_evaluations_run_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_reviews_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReviewStatus"] | null;
                document_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                review_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_review_reviews__review_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                review_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_review_reviews__review_id__correct_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                review_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_review_reviews__review_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path: {
                review_id: string;
            };
            cookie?: {
                docintel_demo?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
